### ISSUE TITLE
XPATH configuration as a string issue

### ISSUE THREAD

**Issue by timramseyjr** [softonic/laravel-intelligent-scraper#13]
In the documentation it says an XPATH configuration can be created as a string:

```
Configuration::create([
    'name' => 'title',
    'type' => 'Item-definition-1',
    'xpaths' => '//*[@id=title]',
]);
```

and "The xpaths field could contain a string or an array of strings"

However if you try add a string you get a `Invalid argument supplied for foreach` from line 38 of softonic/laravel-intelligent-scraper/src/Scraper/Application/XpathFinder.php that expects an array.

**Comment by joskfg** [comment]
You are right. That feature was finally not implemented.

Do you think it would be useful? Do you want to contribute with a PR to add this feature?

**Comment by joskfg** [comment]
Closed issue due to innactivity. If anyone needs it and/or want to collaborate, you are welcome.
