### ISSUE TITLE
Specified key was too long; max key length is 3072

### ISSUE THREAD

**Issue by elliana817** [softonic/laravel-intelligent-scraper#20]
I get `Base table or view not found: 1146 Table 'database.configurations' doesn't exist` .

I know it contain two migration file but I do not know whether I need to copy these file to my project migration directory or we can import/create these table from vendor directory, I do not find regarding these in documentation. I am new to Laravel.

**Comment by elliana817** [comment]
I am able to migrate it but I receive error 

`SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 3072 bytes (SQL: alter table scraped_datasets add primary key scraped_datasets_url_primary(url))`

**Comment by joskfg** [comment]
It is an issue with [Laravel and MySQL character set](https://laravel-news.com/laravel-5-4-key-too-long-error). Closing because this is not a library issue.

**Comment by giulioprinaricotti** [comment]
```
Schema::create('scraped_datasets', function (Blueprint $table) {
            $table->string('url', 1024)->primary(); // <--- THE CULPRIT
            $table->string('type');
            $table->string('variant', 40)->index()->nullable();
            $table->json('data');
            $table->timestamps();
        });``
```

Per MySQL [documentation](https://dev.mysql.com/doc/refman/8.0/en/create-index.html) :

"For example, a prefix can be up to 767 bytes long for InnoDB tables that use the REDUNDANT or COMPACT row format. The prefix length limit is 3072 bytes for InnoDB tables that use the DYNAMIC or COMPRESSED row format. For MyISAM tables, the prefix length limit is 1000 bytes."

Given that we're working with utf8mb4 by default on most laravel installations, each character is 4 bytes long. This makes the url field 1024*4 = 4096 bytes long which is over the 3072 limit even for mysql8. 

Also, I'm not a DB expert but I wouldn't index on such a long field. Wouldn't it be possible to create a hash of the url and use that as an index?

**Comment by joskfg** [comment]
You are right. An URL is not the best primary key, it should be better with some kind of hash. Could you provide a PR?
