### ISSUE TITLE
Does not support last laravel version

### ISSUE THREAD

**Issue by abdosaeedelhassan** [softonic/laravel-intelligent-scraper#22]
[
![Screenshot from 2021-07-02 15-29-53](https://user-images.githubusercontent.com/15355610/124281791-64cab080-db4a-11eb-9d7b-8b4ca25a2179.png)
](url)

also is there an real example how to use this package please?
thank you

**Comment by joskfg** [comment]
I don't see any conflict with the latest laravel version. Compsoser indicates that you are requiring fabpot/goutte 4.0 while this package requires ^3.2.

About the examples, in the README.md there are instructions about how to configure and run it with some complete examples. Are you missing something?

**Comment by abdosaeedelhassan** [comment]
i sorry for late to close this  issue, thank you
